CREATE TABLE llx_frota_uso (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    ref VARCHAR(128) NOT NULL,
    fk_veiculo INTEGER NOT NULL,
    fk_implement INTEGER,
    fk_project INTEGER,
    fk_task INTEGER,
    fk_tipo_operacao INTEGER NOT NULL,
    date_uso DATETIME NOT NULL,
    horimeter_start DOUBLE(24,8) NOT NULL,
    horimeter_end DOUBLE(24,8) NOT NULL,
    worked_hours DOUBLE(24,8) NOT NULL DEFAULT 0,
    area_ha DOUBLE(24,8) NOT NULL DEFAULT 0,
    operator_id INTEGER,
    estimated_hour_cost DOUBLE(24,8) NOT NULL DEFAULT 0,
    estimated_total_cost DOUBLE(24,8) NOT NULL DEFAULT 0,
    note TEXT,
    fk_user_creat INTEGER NOT NULL,
    fk_user_modif INTEGER,
    datec DATETIME NOT NULL,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_frota_uso_ref (entity, ref),
    INDEX idx_frota_uso_entity (entity),
    INDEX idx_frota_uso_veiculo (fk_veiculo),
    INDEX idx_frota_uso_implement (fk_implement),
    INDEX idx_frota_uso_project (fk_project),
    INDEX idx_frota_uso_task (fk_task),
    INDEX idx_frota_uso_operacao (fk_tipo_operacao),
    INDEX idx_frota_uso_date (date_uso)
) ENGINE=innodb;

