CREATE TABLE llx_frota_abastecimento (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    ref VARCHAR(128) NOT NULL,
    fk_veiculo INTEGER NOT NULL,
    fk_product INTEGER NOT NULL,
    fk_warehouse INTEGER NOT NULL,
    fk_stock_movement INTEGER,
    date_fueling DATETIME NOT NULL,
    qty DOUBLE(24,8) NOT NULL,
    unit_price DOUBLE(24,8) NOT NULL DEFAULT 0,
    total_amount DOUBLE(24,8) NOT NULL DEFAULT 0,
    horimeter DOUBLE(24,8),
    odometer DOUBLE(24,8),
    average_consumption DOUBLE(24,8),
    consumption_basis VARCHAR(16),
    status INTEGER NOT NULL DEFAULT 0,
    date_confirmed DATETIME,
    fk_user INTEGER,
    fk_user_confirm INTEGER,
    note TEXT,
    fk_user_creat INTEGER NOT NULL,
    fk_user_modif INTEGER,
    datec DATETIME NOT NULL,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_frota_abastecimento_ref (entity, ref),
    INDEX idx_frota_abastecimento_entity (entity),
    INDEX idx_frota_abastecimento_veiculo (fk_veiculo),
    INDEX idx_frota_abastecimento_product (fk_product),
    INDEX idx_frota_abastecimento_warehouse (fk_warehouse),
    INDEX idx_frota_abastecimento_status (status),
    INDEX idx_frota_abastecimento_date (date_fueling)
) ENGINE=innodb;
