CREATE TABLE llx_frota_veiculo (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    ref VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    fk_veiculo_type INTEGER,
    brand VARCHAR(128),
    model VARCHAR(128),
    year INTEGER,
    plate VARCHAR(32),
    chassis VARCHAR(128),
    asset_number VARCHAR(128),
    horimeter DOUBLE(24,8) NOT NULL DEFAULT 0,
    odometer DOUBLE(24,8) NOT NULL DEFAULT 0,
    estimated_hour_cost DOUBLE(24,8) NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    note TEXT,
    fk_user_creat INTEGER NOT NULL,
    fk_user_modif INTEGER,
    datec DATETIME NOT NULL,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_frota_veiculo_ref (entity, ref),
    INDEX idx_frota_veiculo_entity (entity),
    INDEX idx_frota_veiculo_type (fk_veiculo_type),
    INDEX idx_frota_veiculo_status (status)
) ENGINE=innodb;
