CREATE TABLE llx_frota_manutencao (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    entity INTEGER NOT NULL DEFAULT 1,
    ref VARCHAR(128) NOT NULL,
    fk_veiculo INTEGER,
    fk_implement INTEGER,
    type VARCHAR(16) NOT NULL DEFAULT 'preventiva',
    status INTEGER NOT NULL DEFAULT 0,
    date_planned DATETIME,
    date_start DATETIME,
    date_end DATETIME,
    due_horimeter DOUBLE(24,8),
    due_odometer DOUBLE(24,8),
    horimeter DOUBLE(24,8),
    odometer DOUBLE(24,8),
    is_periodic TINYINT NOT NULL DEFAULT 0,
    period_days INTEGER,
    period_hours DOUBLE(24,8),
    period_km DOUBLE(24,8),
    fk_origin_maintenance INTEGER,
    fk_next_maintenance INTEGER,
    description TEXT NOT NULL,
    labor_cost DOUBLE(24,8) NOT NULL DEFAULT 0,
    parts_cost DOUBLE(24,8) NOT NULL DEFAULT 0,
    total_cost DOUBLE(24,8) NOT NULL DEFAULT 0,
    fk_user_assigned INTEGER,
    fk_user_creat INTEGER NOT NULL,
    fk_user_modif INTEGER,
    datec DATETIME NOT NULL,
    tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_frota_manutencao_ref (entity, ref),
    INDEX idx_frota_manutencao_entity (entity),
    INDEX idx_frota_manutencao_veiculo (fk_veiculo),
    INDEX idx_frota_manutencao_implement (fk_implement),
    INDEX idx_frota_manutencao_status (status),
    INDEX idx_frota_manutencao_date (date_start),
    INDEX idx_frota_manutencao_planned (date_planned),
    INDEX idx_frota_manutencao_due_horimeter (due_horimeter),
    INDEX idx_frota_manutencao_due_odometer (due_odometer),
    INDEX idx_frota_manutencao_periodic (is_periodic),
    INDEX idx_frota_manutencao_next (fk_next_maintenance),
    UNIQUE INDEX uk_frota_manutencao_origin (entity, fk_origin_maintenance)
) ENGINE=innodb;
